---
deployment:
  tasks:
    - export DEPLOYPATH=/home/thedigiologist/domains/asharindustries.com/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
